#!/bin/bash

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - references"
    NODE_PARAMS="--inspect=0.0.0.0:30050"
fi

exec /sbin/setuser www-data /usr/bin/node $NODE_PARAMS /overleaf/services/references/app.js >> /var/log/sharelatex/references.log 2>&1