FROM phusion/baseimage:jammy-1.0.1

LABEL \
    org.opencontainers.image.title="Docker Image of TeXLive" \
    org.opencontainers.image.authors="ayaka-notes <public@ayaka.space>" \
    org.opencontainers.image.source="https://github.com/ayaka-notes/overleaf" \
    org.opencontainers.image.licenses="MIT"

# 非交互模式
ENV DEBIAN_FRONTEND noninteractive

# 参数-年份
ARG TEXLIVE_Version=2014

# 这里必须用http或者ftp，因为https在perl中会被认为不匹配
ARG TEXLIVE_MIRROR=http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/${TEXLIVE_Version}/tlnet-final
# ftp://tug.org/historic/systems/texlive/${TEXLIVE_Version}/tlnet-final


# 拷贝LatexMk文件到/usr/local/share/latexmk/LatexMk
COPY LatexMk /usr/local/share/latexmk/LatexMk
COPY patchSynctex.R /usr/local/bin/
COPY run-chktex.sh /usr/local/bin/

# 设置权限
RUN chmod 777 -R /usr/local/bin/ && \
    chmod 777 -R /usr/local/share/latexmk/

# 安装依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    fontconfig inkscape pandoc python3-pygments wget python3 \
    gnupg gnuplot perl-modules perl ca-certificates git ghostscript \
    qpdf r-base-core

# 安装字体
RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections \
&& apt-get update && apt-get install -y ttf-mscorefonts-installer \
&& apt update && apt search ^fonts | grep -o '^fonts[^/]*' | xargs apt install -y

# 感谢Overleaf的Dockerfile
# 安装 texlive
RUN mkdir /install-tl-unx \
&&  wget --quiet https://tug.org/texlive/files/texlive.asc \
&&  gpg --import texlive.asc \
&&  rm texlive.asc \
&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz \
&&  tar -xz -C /install-tl-unx --strip-components=1 -f install-tl-unx.tar.gz \
&&  rm install-tl-unx.tar.gz* \
&&  echo "tlpdbopt_autobackup 0" >> /install-tl-unx/texlive.profile \
&&  echo "tlpdbopt_install_docfiles 0" >> /install-tl-unx/texlive.profile \
&&  echo "tlpdbopt_install_srcfiles 0" >> /install-tl-unx/texlive.profile \
&&  echo "selected_scheme scheme-full" >> /install-tl-unx/texlive.profile \
    \
&&  /install-tl-unx/install-tl \
      -profile /install-tl-unx/texlive.profile \
      -repository ${TEXLIVE_MIRROR} \
    \
&&  rm -rf /install-tl-unx
# &&  $(find /usr/local/texlive -name tlmgr) path add \
# &&  tlmgr path add \

# 配置 /usr/local/texlive/${TEXLIVE_Version}/texmf.cnf, 使得LaTeX可以使用shell-escape
RUN echo "shell_escape = t" >> /usr/local/texlive/${TEXLIVE_Version}/texmf.cnf && \
    echo "openout_any = a" >> /usr/local/texlive/${TEXLIVE_Version}/texmf.cnf && \
    echo "openin_any = a" >> /usr/local/texlive/${TEXLIVE_Version}/texmf.cnf

# 设置环境变量
ENV PATH="/usr/local/texlive/${TEXLIVE_Version}/bin/x86_64-linux:${PATH}"
